### ISSUE TITLE
Authorization using securityDefinitions and security parameter

### ISSUE THREAD

**Issue by Faris-AH** [epiphone/routing-controllers-openapi#11]
I am using addition properties for authorization 
```
 {
     "components": { schemas },
      "info": { title: 'Test, version: '0.0.0.1' },
      "securityDefinitions": {
        "test_api": {
            "description": "API Token",
            "type": "http",
            "name": "test_api",
            "in": "header"
        }
      }
```
and in controller
```
  @Authorized()
  @Post("/website")
  @OpenAPI({
    "description": 'List all websites',
    "security": [{
      "test_api": []
    }]
  })
  async Create(
    @Body() websiteData: CreateWebsiteRequest): Promise<any> {
    return await this._websiteService.Create(websiteData);
  }
```
I know authorization feature is mission in it. Can i implement authorization in this way?
Thanks :)

**Comment by epiphone** [comment]
Hi, something along those lines should do the trick, yes. Note though that in OpenAPI 3 the way security schemas are defined changed a bit: https://swagger.io/docs/specification/authentication/#changes

**Comment by klassicd** [comment]
There is a good example here https://github.com/epiphone/routing-controllers-openapi/blob/master/sample/01-basic/app.ts
