### ISSUE TITLE
Reference error in array of objects

### ISSUE THREAD

**Issue by Faris-AH** [epiphone/routing-controllers-openapi#13]
`export class City {
  @IsNotEmpty()
  City: string;

  @IsNotEmpty()
  State: string;
}
export class CreateEntityRequest {
  @IsNotEmpty()
  FirstName: string;

  @IsOptional()
  MiddleName: string;

  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => City)
  Cities: City[]
}
`
Accroding to the above code components.schemas.CreateEntityRequest.properties.Cities.items["$ref"]  = #/components/schemas/Array

It should contain

components.schemas.CreateEntityRequest.properties.Cities.items["$ref"]  = #/components/schemas/City

**Comment by epiphone** [comment]
Hi! Did you remember to define the `classTransformerMetadataStorage` property in class-validator-jsonschema config? Along the lines of:

```typescript
import { defaultMetadataStorage } from 'class-transformer/storage'
import { validationMetadatasToSchemas } from 'class-validator-jsonschema'

const schemas = validationMetadatasToSchemas(metadatas, {
  classTransformerMetadataStorage: defaultMetadataStorage // <-- Define class-transformer metadata in options
})
```

**Comment by Faris-AH** [comment]
Oops sorry. Thanks for your help.
