### ISSUE TITLE
Missing / in $ref when using ValidateNested

### ISSUE THREAD

**Issue by quentinus95** [epiphone/routing-controllers-openapi#15]
Hi,

Using the following classes:

```ts
export default class User {
  @ValidateNested()
  provider!: Provider
}
```

I get the following generated json:

```
"User":{[...],"provider":{"$ref":"#/components/schemasProvider"}}
```

-> There is a missing / in the $ref before "Provider"

When adding a / in the `refPointerPrefix` contrary to what we can see here: https://github.com/epiphone/routing-controllers-openapi/blob/master/sample/01-basic/app.ts it fixes the issue

**Comment by epiphone** [comment]
Oh yeah, `refPointerPrefix` should indeed end with a slash. Pushed a fix, thanks!

**Comment by guillaume-roy** [comment]
Hi, Could you update the package on NPM please ? Thanks !

**Comment by epiphone** [comment]
@guillaume-roy it was just a matter of fixing a typo in sample code, so nothing to update on NPM. Check the fixed sample here: https://github.com/epiphone/routing-controllers-openapi/blob/master/sample/01-basic/app.ts#L22

**Comment by guillaume-roy** [comment]
Yes ... my bad. Thanks !
