### ISSUE TITLE
Older TS fails to recognize Array Union as an Array

### ISSUE THREAD

**Issue by Downchuck** [epiphone/routing-controllers-openapi#24]
```
node_modules/routing-controllers-openapi/build/decorators.d.ts:5:55 - error TS2370: A rest parameter must be of an array type.

5 export declare function OpenAPI(spec: OpenAPIParam): (...args: [Function] | [object, string, PropertyDescriptor]) => void;
                                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/routing-controllers-openapi/build/decorators.d.ts:12:6 - error TS2370: A rest parameter must be of an array type.

12 }): (...args: [Function] | [object, string, PropertyDescriptor]) => void;
```

Likely fixed as of this year in TSC:
https://github.com/Microsoft/TypeScript/issues/23440

**Comment by epiphone** [comment]
Support for array spread types was [added in typescript 3.0](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html#tuples-in-rest-parameters-and-spread-expressions), I'd advise you to upgrade if possible.

**Comment by Downchuck** [comment]
The bug is in 3.0 -- the spread type is supported for arrays but the inline union type is misinterpreted. Note the error identifies the rest argument correctly but does not see the type as an array.

**Comment by epiphone** [comment]
Ah, I see. Upgrading to latest typescript fixes the issue though?

**Comment by Downchuck** [comment]
I believe so - at approx 3.3
