### ISSUE TITLE
Is there built-in support for validating API responses against definition/swagger?

### ISSUE THREAD

**Issue by chinhdo** [epiphone/routing-controllers-openapi#36]
Hi, I am trying to find a way to validate our API responses to make sure they are valid during testing. We are already using routing-controllers-openapi to document our APIs and generate swaggers. I tried to look at the docs/code but couldn't find the answer myself. Thanks for any info. Chinh

**Comment by epiphone** [comment]
Nope, this library is purely for generating OpenAPI. Check the [routing-controllers docs](https://github.com/typestack/routing-controllers#auto-validating-action-params) for how to do request validation.

**Comment by chinhdo** [comment]
Thanks @epiphone .

**Comment by kenberkeley** [comment]
My temp workaround: https://github.com/typestack/routing-controllers/issues/745#issuecomment-1132915108
