### ISSUE TITLE
is there a feature about showing UI?

### ISSUE THREAD

**Issue by Q00** [epiphone/routing-controllers-openapi#37]
Hi !
I am glad to discover this code.
It is good to show api spec with using routing-controller. But I wanna know how to show UI using api spec.
So Now I am trying to use swagger-ui-express module with routing-controllers-openapi.
did this feature have already build in routing-controllers-openapi?

**Comment by epiphone** [comment]
Nope, that's beyond the scope of this library. You're heading in the right direction with swagger-ui-express et al!

**Comment by yardenshoham** [comment]
@Q00 
I'd recommend [ReDoc](https://github.com/Redocly/redoc/).

**Comment by Q00** [comment]
> @Q00
> I'd recommend [ReDoc](https://github.com/Redocly/redoc/).

Hi @yardenshoham 
Wow, that's good library.

I just use swagger-ui-express like this
![image](https://user-images.githubusercontent.com/31264094/73240599-c7e04700-41e2-11ea-93ed-ba80885c1cb0.png)

Thank you for your replying!
