### ISSUE TITLE
Not able to add component schema

### ISSUE THREAD

**Issue by pankaj884** [epiphone/routing-controllers-openapi#4]
This is my view model of a single class, please tell how I can add it to the component schema.

```
import { MaxLength, IsEmail, Length, IsArray, IsAscii, ArrayUnique, ArrayMaxSize, IsNotEmpty } from "class-validator";
import { NormalizeEmail } from "class-sanitizer";
import { BaseViewModel } from "./BaseViewModel";

export class UserViewModel extends BaseViewModel {

    @IsNotEmpty()
    @MaxLength(256)
    name: string;

    @IsEmail()
    @NormalizeEmail()
    email: string;

    @IsAscii()
    @Length(6, 72)
    password: string;

    @IsArray()
    @ArrayUnique()
    @ArrayMaxSize(10)
    roles: string[];
}

```

**Comment by epiphone** [comment]
1. Check the [class-validator-jsonschema docs](https://github.com/epiphone/class-validator-jsonschema#usage) on how to access `class-validator` metadata.
2. Use `class-validator-jsonschema` to generate JSON schema out of the metadata, adding the `refPointerPrefix` parameter as [demonstrated on the docs](https://github.com/epiphone/routing-controllers-openapi#validation-classes).
3. Supply your schemas inside the `additionalProperties` parameter when generating OpenAPI spec [as shown here](https://github.com/epiphone/routing-controllers-openapi#validation-classes).

That should do the trick!
