### ISSUE TITLE
Missing tslib module

### ISSUE THREAD

**Issue by alxdrg** [epiphone/routing-controllers-openapi#42]
The `tslib` module was removed in version `1.8` but is required by typescript in the transpiled code. See the `importHelpers` flag set in `tsconfig.json`.

From typescript documentation:
```
--importHelpers | boolean | false | Import emit helpers (e.g. __extends, __rest, etc..) from tslib
```

This issue makes all the applications, that doesn't have the `tslib` module installed as its dependencies or by other modules, to break with the following error:
```
Error: Cannot find module 'tslib'
Require stack:
- /app/node_modules/routing-controllers-openapi/build/index.js
```

**Comment by epiphone** [comment]
Restored `tslib` in `1.8.1`, thanks for notifying!
