### ISSUE TITLE
Infer Response Type from endpoint

### ISSUE THREAD

**Issue by nolazybits** [epiphone/routing-controllers-openapi#48]
It seems that using the new(ish)  ReturnType introduced in typescript 2.8 one should be able to get the type returned by the endpoint?

documentation
https://www.typescriptlang.org/docs/handbook/utility-types.html#returntypet
https://github.com/Microsoft/TypeScript/pull/21847

Promise example
https://jpwilliams.dev/how-to-unpack-the-return-type-of-a-promise-in-typescript

Your thoughts?

**Comment by epiphone** [comment]
This library operates in runtime, not type level. So what we're after is a runtime value describing the return type, not the return type itself. To access one of those we use Typescript's reflection API which currently does not preserve generic type parameters: https://github.com/Microsoft/TypeScript/issues/10576.
