### ISSUE TITLE
Always getting an extra text/html content type on responses

### ISSUE THREAD

**Issue by vmenge** [epiphone/routing-controllers-openapi#57]
Hi! Really appreciate what you've done here, very useful.
One issue I've been getting is that for my responses, I always get an extra content type of text/html.

**On my controller**
```
    @Put('/deactivations')
    @OpenAPI({
        description: 'Deactivates an article.'
    })
    @ResponseSchema(ResponseArticle, {
        contentType: 'application/json',
        statusCode: 200
    })
    async deactivate(@Body() deactivationArticle: DeactivationArticle): Promise<ResponseArticle> {
        return {} as ResponseArticle;
    }
```

**Generated spec**
```
"responses": {
          "200": {
            "content": {
              "text/html; charset=utf-8": {},
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseArticle"
                }
              }
            },
            "description": ""
          }
        },
```

ResponseArticle is just a normal class with `class-validator` decorators and the `@JSONSchema` decorator from `class-validator-jsonschema` but only on fields.

I keep getting this extra `text/html` in the content object. Not sure if I'm doing anything wrong or if it's a bug.
Would appreciate any help :-)

**Comment by epiphone** [comment]
Hey, are you using routing-controller's JsonController class? https://github.com/typestack/routing-controllers#working-with-json

**Comment by vmenge** [comment]
Seems that was it. Wew, I feel pretty stupid.
Thanks @epiphone
