### ISSUE TITLE
Deprecated tag not being added to doc

### ISSUE THREAD

**Issue by WRostom** [epiphone/routing-controllers-openapi#6]
I used the OpenAPI decorator to add the deprecated tag to the documentation and it didn't read it for some reason.

Code
![screenshot from 2018-06-22 16-38-05](https://user-images.githubusercontent.com/4014846/41782719-4c907d46-763b-11e8-99a7-cf5a45d40bfa.png)

swagger.json file
![screenshot from 2018-06-22 16-39-27](https://user-images.githubusercontent.com/4014846/41782729-52d97356-763b-11e8-9633-53600042bbef.png)

**Comment by epiphone** [comment]
There was a bug in how the library cleans up empty properties; I didn't realize `_.isEmpty(true)` resolves to `true`. Pushed a patch, thanks for the heads-up!

**Comment by WRostom** [comment]
Any time. Thank _you_ for doing the actual hard work.
