### ISSUE TITLE
Error @IsArray response

### ISSUE THREAD

**Issue by lucasvieceli** [epiphone/routing-controllers-openapi#60]
When I use "@IsArray ()" in the response, it is not displaying

example:
![image](https://user-images.githubusercontent.com/1795678/96728036-18f42480-138a-11eb-8b28-8db94b843610.png)

Controller
```
 @Get()
    @ResponseSchema(PacientesPaginationResponse)
    async getAll(
        @QueryParam("limit") limit: number, 
        @QueryParam("page") page: number, 
        @QueryParam("cpf") cpf: string, 
        @QueryParam("establishmentId") establishmentId: string, 
        @CurrentUser() currentUser
    ) {
        if(!cpf && !establishmentId){
            throw new ForbiddenError()
        }

        return await patientService.getPagination({
            page,
            limit,
            params:{
                cpf,
                establishmentId
            },
            currentUser
        });
    }
```

Response
```
import { IsArray, IsString } from "class-validator";
import { PaginationResponse } from "../../../utils/pagination-response";

class PacientesPaginationListResponse {
    @IsString()
    id = 'teste';

    @IsString()
    nome: string;
    
    @IsString()
    password: string;
    
    @IsString()
    role: string;
    
    @IsString()
    cpf: string;
    
    @IsString()
    email: string;

}

export class PacientesPaginationResponse extends PaginationResponse {
    
    @IsArray()
    Items: Array<PacientesPaginationListResponse>
    
}
```

**Comment by epiphone** [comment]
Try https://github.com/epiphone/class-validator-jsonschema#validatenested-and-arrays

**Comment by fega** [comment]
@epiphone I'm doing that:
![image](https://user-images.githubusercontent.com/6069807/99819862-05211700-2b1e-11eb-91fb-17ea686a1449.png)

but still

![image](https://user-images.githubusercontent.com/6069807/99820050-4285a480-2b1e-11eb-8f53-9bb936ff9f71.png)

**Comment by kaifresh** [comment]
@epiphone just wondering if there was any more insight into this? I too am facing this problem

![image](https://user-images.githubusercontent.com/8577170/105575430-b747ba00-5dbf-11eb-92b7-db5bb8405d6e.png)


resulting in

![image](https://user-images.githubusercontent.com/8577170/105575438-c3cc1280-5dbf-11eb-81d2-80ece1345977.png)

**Comment by epiphone** [comment]
1) Did you specify the `classTransformerMetadataStorage` config option?
```ts
const schemas = validationMetadatasToSchemas({
  classTransformerMetadataStorage: defaultMetadataStorage, // 2) Define class-transformer metadata in options
})
```

2) Which versions are you using? What does `npm ls class-validator-jsonschema class-transformer` output?
