### ISSUE TITLE
Field of type any

### ISSUE THREAD

**Issue by bmoshe** [epiphone/routing-controllers-openapi#64]
Hi guys,

I have a weird situation where one of my DTO objects has field of type `any`, openapi converts it to `"$ref": "#/components/schemas/Object"`, which causes typegen to fail, because it doesn't recognize `Object`.

This field is only decorated with `@IsObject()`
What am I doing wrong here?

**Comment by exejutable** [comment]
Same problem here, i make a workaround replacing all the `"$ref": "#/components/schemas/Object"` for `"type": "object"`

`  let file = JSON.stringify(swaggerFile, null, 4).split('"$ref": "#/components/schemas/Object"').join('"type": "object"')
`

waiting form a solution

**Comment by epiphone** [comment]
Added handling for `IsObject` in https://github.com/epiphone/class-validator-jsonschema/releases/tag/v2.1.0.

Thanks for the heads-up :+1:
