### ISSUE TITLE
Cannot read property 'route' of undefined

### ISSUE THREAD

**Issue by aliabbasrizvi** [epiphone/routing-controllers-openapi#67]
Hi

I am trying to define an abstract controller as described here: https://github.com/typestack/routing-controllers#controller-inheritance, but keep getting the issue `TypeError: Cannot read property 'route' of undefined` originating at https://github.com/epiphone/routing-controllers-openapi/blob/master/src/generateSpec.ts#L16. Is there something I need to be doing differently?

Thanks

**Comment by epiphone** [comment]
Try upgrading to latest dependency versions, and if the problem persists post your code here so that the bug can be reproduced.

**Comment by Jobayerdev** [comment]
![image](https://user-images.githubusercontent.com/34404032/120316889-c0154300-c2ff-11eb-8a08-c9df14a3b868.png)
 Can anyone please help me
